"""empty message

Revision ID: 7cbb25deee80
Revises: 3ca3c4f83ef7
Create Date: 2023-08-18 23:14:48.408688

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash #per c4---------------------------------------------


# revision identifiers, used by Alembic.
revision = '7cbb25deee80'
down_revision = '3ca3c4f83ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Before the schema change, set a default password hash
    temp_hash = generate_password_hash('temp_password')
    op.execute(f'UPDATE "user" SET password_hash = \'{temp_hash}\' WHERE password_hash IS NULL')
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('caption', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('post')
    # ### end Alembic commands ###
